package com.mahsum.puzzle;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.Environment;

public class Application extends android.app.Application {

  
  private static Application application;
  private static String imagesRootDir;
  private static Bitmap[] masks;

  @Override
  public void onCreate() {
    super.onCreate();
    application = this;
    imagesRootDir = Environment.getExternalStorageDirectory().toString() + "/puzzle";
    loadMasks();
  }

  private static void loadMasks() {
    masks = new Bitmap[9];

    BitmapFactory.Options options = new BitmapFactory.Options();
    options.inScaled = false;
    options.inMutable = true;
    /*
    Learn what density means. How it is used.
    Masks generated by MaskGenerator.class has density of 420.
    Density of a bitmap can be learned by bitmap.getDensity()
     */
    options.inDensity = 420;
    masks[0] = BitmapFactory.decodeResource(application.getResources(), R.drawable.zero, options);
    masks[1] = BitmapFactory.decodeResource(application.getResources(), R.drawable.one, options);
    masks[2] = BitmapFactory.decodeResource(application.getResources(), R.drawable.two, options);
    masks[3] = BitmapFactory.decodeResource(application.getResources(), R.drawable.three, options);
    masks[4] = BitmapFactory.decodeResource(application.getResources(), R.drawable.four, options);
    masks[5] = BitmapFactory.decodeResource(application.getResources(), R.drawable.five, options);
    masks[6] = BitmapFactory.decodeResource(application.getResources(), R.drawable.six, options);
    masks[7] = BitmapFactory.decodeResource(application.getResources(), R.drawable.seven, options);
    masks[8] = BitmapFactory.decodeResource(application.getResources(), R.drawable.eight, options);
  }

  public static Bitmap getMask(int index){ return masks[index]; }
  
  public static String getImagesRootDir(){ return imagesRootDir; }

}
